language: cpp

compiler:
  - gcc
  - clang

before_script:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y
  - sudo apt-get update -q
  - sudo apt-get install qt5-default qttools5-dev-tools -q
  - mkdir build
  - cd build
  - cmake ..

script: make